---
language: python
python: "2.7"
sudo: required
dist: xenial

services:
  - docker

matrix:
  fast_finish: true

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-lxc/stable'
    - sourceline: 'ppa:wireguard/wireguard'
    packages:
    - python-pip
    - lxc
    - lxc-templates
    - expect-dev
    - debootstrap
    - shellcheck
    - tree
    - linux-headers-$(uname -r)
    - wireguard-dkms
    - wget
    - build-essential
    - libssl-dev
    - libffi-dev
    - python-dev
    - cloud-utils

cache:
  pip: true

env:
  - NAME=qemu-artful RELEASE=artful
  # - NAME=qemu-bionic RELEASE=bionic
  # - NAME=docker RELEASE=bionic

before_install:
  - wget https://cloud-images.ubuntu.com/${RELEASE}/current/${RELEASE}-server-cloudimg-amd64.img -O /tmp/${RELEASE}.img
  # - test "${LXC_NAME}" != "docker" || docker build -t travis/algo .

install:
  - ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''
  - |
    cat > ~/cloud-init.yml << EOF
    #cloud-config
    users:
      - defaults
      - name: ubuntu
        ssh-authorized-keys:
          - $(cat ~/.ssh/id_rsa.pub)
        sudo: ['ALL=(ALL) NOPASSWD:ALL']
        groups: sudo
        shell: /bin/bash
    EOF
  - cloud-localds --disk-format qcow2 /tmp/cloud-init.img ~/cloud-init.yml
  - |
    qemu-system-x86_64 \
      -daemonize \
      -nographic \
      -display none \
      /tmp/${RELEASE}.img \
      -m 256 -smp 4 \
      -net user,hostfwd=tcp::2222-:22 -net nic \
      -device virtio-blk-pci,drive=cloud -drive if=none,id=cloud,file=/tmp/cloud-init.img,format=raw
  - pip install -r requirements.txt
  - pip install ansible-lint
  - gem install awesome_bot
  - ansible-playbook --version
  - tree . -L 2

script:
  # - awesome_bot --allow-dupe --skip-save-results *.md docs/*.md --white-list paypal.com,do.co,microsoft.com,https://github.com/trailofbits/algo/archive/master.zip,https://github.com/trailofbits/algo/issues/new
  # - shellcheck algo
  # - ansible-lint deploy.yml users.yml deploy_client.yml
  - ansible-playbook deploy.yml --syntax-check
  - ./tests/local-deploy.sh

after_script:
  - ./tests/update-users.sh

notifications:
  email: false
